import React, {Component} from 'react'
import './assets/policy.css'

export class Policy extends Component {
    render() {
        return (
            <div className='into-container-article ' id='privacy'>

                {/*display  in pc and pad*/}
                <div className='article-share-buttons pc-block'>
                    <a href="https://www.facebook.com/sharer/sharer.php?app_id=472756216419966&sdk=joey&u=https://intomore.com/you/Missed-Connections-What-The-Craigslist-Personals-Section-Meant-to-LGBTQ-People/9a85f1945daa494c&display=popup&ref=plugin&src=share_button" className="social-svg facebook-svg">&nbsp;</a>
                    <a href="https://twitter.com/share" className="social-svg twitter-svg">&nbsp;</a>
                </div>

                <div className='privacy-content'>
                    <div className='row'>
                        <div className='col-xs-12 col-md-12'>
                            <h1 className='column-title '>
                                <span className='content-title'>Privacy Policy</span>
                            </h1>
                            <div className='content'>
                                <h2>GRINDR PRIVACY POLICY</h2>
                                <p>
                                    By accessing the website at http://grindr.com (Grindr SiteÓ), the Grindr mobile application (e.g., Grindr iOS, Grindr iOS Xtra, Grindr Android, Grindr Android Xtra) (Grindr AppÓ), Gaymoji by Grindr (GaymojiÓ) or the website at http://intomore.com (INTO SiteÓ and collectively with the Grindr Site, the Grindr App, and Gaymoji, the Grindr ServicesÓ), which are provided by Grindr LLC, with a mailing address of PO Box 69176, West Hollywood, California 90069 (GrindrÓ), you expressly consent to the collection, use and disclosure of your Personal Data (defined below) in accordance with this Privacy Policy. You also consent to GrindrÕs cookie policies, as described herein.
                                </p>
                                <p><u>Types Of Data We Collect.</u></p>
                                <p>
                                    We collect personal data and non-personal data about you.  Personal DataÓ means any data that allows someone to identify or contact you.
                                </p>
                                <p>
                                    The following provides examples of the types of data that we collect, and how we collect them.  Note that not all of the Grindr Services collect all of the data listed below:
                                </p>
                                <p><strong>Account Credentials.</strong> We may require you to provide an email address and password to use the Grindr App or other Grindr Services.  We may also ask you to provide your phone number for account authentication purposes.</p>
                                <p><strong>Device Information.</strong> We may collect certain software and hardware information about your Device. For example, we may collect an ID that is unique to the device or browser on which you install and/or access the Grindr Services (Device IDÓ and Device,Ó respectively). </p>
                                <p><strong>Location and Distance Information.</strong>When you use the Grindr App, we will collect your location to determine your distance from other users (Distance InformationÓ) through the GPS, Wi-Fi, and/or cellular technology in your Device. Your last known location may be stored for the purpose of calculating Distance Information between you and other users.</p>
                                <p><strong>Log Files.</strong>We may collect information from you, including your browser type, operating system, Internet Protocol (IP) address (a number that is automatically assigned to your computer when you use the Internet, which may vary from session to session), domain name, and/or a date/time stamp for your visit. We also use cookies and URL information to gather information regarding the date and time of your visit and the information for which you searched and which you viewed. CookiesÓ are small pieces of information that a website sends to your computerÕs hard drive while you are viewing a web site. We may use both session cookies (which expire once you close your web browser) and persistent cookies (which stay on your Device until you delete them) to provide you with a more personal and interactive experience on the Grindr Services and to improve our marketing efforts, including through the use of targeted advertising. Persistent cookies we place may be removed by following instructions provided by your browser.  If you choose to disable cookies, some areas or features of the Grindr Services may not work properly.
                                </p>
                                <p><strong>Messages.</strong>When you send a message (which may include photos, location, audio, or video) to other users of the Grindr Services, we may retain the message for archival purposes or as otherwise allowed by law.
                                </p>
                                <p><strong>Profile Information.</strong>We may collect Personal Data from you. For example, in the Grindr App, we may collect your photo, display name, relationship status, ethnicity, age or date of birth, geo-location data, email address, password for the Grindr Services, height, weight, social network link, Looking For,Ó About Me,Ó Favorites,Ó Blocks,Ó TribesÓ and any other information that you voluntarily add to your profile on the Grindr App or that is generated through your use of the Grindr Services. You may also have the option to provide information concerning health characteristics, such as your HIV status or Last Tested Date. Remember that if you choose to include information in your profile, and make your profile public, that information will also become public. As a result, you should carefully consider what information to include in your profile.</p>
                                <p><strong>Purchases.</strong>We collect information necessary to complete purchases.  This may include, among other things, your name, credit card information, billing information, address, telephone number, and email address.</p>
                                <p>
                                    Grindr does not receive or process credit card information directly.  We currently use Stripe or Google Play for purchases on Android devices and Apple for purchases on Apple devices. Please review their privacy policies at
                                    <a href='https://stripe.com/us/privacy' className='blue'>https://stripe.com/us/privacy</a>, <span className='orange'>https://www.google.com/policies/privacy/</span>,and  <span className='orange'>http://www.apple.com/privacy</span>, respectively, to better understand their practices. The Grindr Services may include links to purchase Grindr merchandise from our third party service provider. If you purchase such merchandise, the third party service providerÕs terms of use and privacy policy apply. We currently use Shopify for Grindr gear purchases. Please review their terms of service at <span className='orange'>https://www.grindrstore.com/pages/terms-conditions</span> and privacy policy at <span className='orange'>https://www.grindrstore.com/pages/privacy-policy</span> to better understand their practices.
                                </p>
                                <p>
                                    Note that our third party service providers may provide certain information to us (e.g., your name, phone number, partial credit card number, and email address).
                                </p>
                                <p><strong>Feedback/Support.</strong>If you provide us feedback or contact us for support we will collect your name and e-mail address and possibly other Personal Data, as well as any other content that you send to us in order to reply and address any issue. If you contact us for support, we may also collect and retain certain technical diagnostic data, such as your phone model.</p>
                                <p><strong>Mailing List.</strong>When you sign up for the Grindr Services, we may collect your email address to send you Grindr news, Grindr Services updates, the latest information on products and services, and third party offers.</p>
                                <p><strong>Surveys.</strong>When you participate in a survey, we may collect additional information that you provide through the survey.  If the survey is provided by a third party service provider, the third partyÕs privacy policy applies to the collection, use, and disclosure of your information. Unless noted otherwise, we use Survey Monkey for surveys.</p>
                                <p><strong>Partner Promotion.</strong>We may collect information that you provide as part of a Partner Promotion (defined below).</p>
                                <p><strong>Third Party Platforms.</strong>If you use or connect to the Grindr Site or download the Grindr Services through a third party platform, such as Facebook, you allow us to access and/or collect certain information from your third party platform profile/account.  We may also access information contained in cookies placed on your Device by the third party platform.  Note that we may share this information with the third party platform for their use.</p>
                                <p><strong>Third Party Tracking.</strong>Our advertisers and partners may also use their own cookies or other tracking technology which may collect information about you within the Grindr Services. We do not control use of these tracking technologies.</p>
                            </div>
                            <div className='sm'>
                                <p><u>Use And Processing Of Your Personal Data.</u></p>
                                <p>In addition to the uses described above, we use your Personal Data in the following ways:</p>
                                <p><strong>Identify You.</strong>To identify you as a user on the Grindr Services.</p>
                                <p><strong>Provide Products and Services.</strong>To provide the products and services you request, including the Grindr Services.</p>
                                <p><strong>Improve Services.</strong>To improve the Grindr Services.</p>
                                <p><strong>Communicate with you.</strong>To respond to your inquiries related to support, employment opportunities, or other requests, and to send Promotional Emails to those users that request or authorize them.</p>
                                <p><strong>Partner Promotions.</strong>To conduct a Partner Promotion that you request.</p>
                                <p><strong>Marketing and Advertising.</strong>For marketing and promotional purposes, including to inform you of products, services or offers of Grindr, our related companies or business partners that may be of interest to you.</p>
                                <p><strong>Administration.</strong>For internal administrative purposes, as well as to administer or manage our relationship with you, including to communicate with you regarding your use of Grindr Services.</p>
                                <p><strong>Employment.</strong> If you apply for employment with Grindr or currently work for Grindr, to manage your employment application, assess your qualifications, and manage your employment with us (applies solely to the Grindr Site).</p>
                                <p><u>Sharing Of Personal Data.</u></p>
                                <p>In addition to the specific situations discussed above, we disclose Personal Data in the following situations:</p>
                                <p><strong>User Profiles.</strong>The Grindr App is a social networking platform that is designed to allow users to share information.  When you use the Grindr App, your Profile Information is public, and other users of the Grindr App can see your Profile Information and other Personal Data (including sensitive personal data) posted by you.  For example, other users can search for you, search for your profile characteristics, or see you listed as being in their vicinity. Do not include information in your profile that you want to keep private.  While the Grindr App may permit you to make certain items (e.g., Profile Information, preferences, opinions of other users, or other information) non-public, sophisticated users who use the Grindr App in an unauthorized manner may nevertheless be able to obtain this information and may be able to determine your identity. </p>
                                <p><strong>Distance Information.</strong> The Grindr App is designed to allow users to share Distance Information. As a result, Distance Information is public, and other users of the Grindr App can see your Distance Information (including how many feet or meters you are from them). Grindr App users can use the search feature in the Grindr App to search for other users by distance or in a particular geographic vicinity. Your Distance Information will be used for these searches. Sophisticated users who use the Grindr App in an unauthorized manner, or other users who change their location while you remain in the same location, may use this information to determine your exact location and may be able to determine your identity.  Please note: even if you choose to hide your Distance Information, the Grindr App will continue to sort and display your profile based on your relative distance from other users, so your Distance Information may still be approximated by other users. Thus, even if you choose to hide your Distance Information, others may nevertheless be able to determine your location.</p>
                                <p><strong>Third Party Tracking Companies. </strong>We may share your hashed Device ID, Profile Information, Distance Information, and demographic information with our advertising and analytics partners. These third parties may also collect information directly from you as described in this Privacy Policy. The privacy policy of these third party companies applies to their collection, use and disclosure of your information. For example, one of our many partners is Google Analytics which collects information anonymously and report website trends without identifying individual visitors.</p>
                                <p><strong>Third Party Service Providers.</strong> We may share your Personal Data with third party service providers to: provide you with the Grindr Services; conduct quality assurance testing; provide technical support; and/or to provide other services to Grindr.  Except as otherwise stated in this Privacy Policy, these third party service providers are required by contract not to use your Personal Data other than to provide the services requested by Grindr.</p>
                                <p><strong>Partner Promotion.</strong> We may offer contests, sweepstakes, or other promotions with third party partners.  If you decide to enter a contest, sweepstakes, or promotion that is sponsored by a third party partner the information that you provide will be shared with us and with them.  Their use of your information is not governed by this privacy policy.</p>
                                <p><strong>Affiliates and Acquisitions.</strong> We may share your Personal Data with our parent company, any subsidiaries, joint ventures, or other companies under common control.  If another company acquires our company, business, or our assets, that company will possess the Personal Data collected by us and will assume the rights and obligations regarding your Personal Data as described in this Privacy Policy.</p>
                                <p><strong>Other Disclosures.</strong>Grindr may disclose Personal Data in response to subpoenas, warrants, or court orders, or in connection with any legal process, or to comply with relevant laws; to establish or exercise our rights to defend against legal claims; if we believe it is necessary to investigate, prevent, or take action regarding illegal activities, suspected fraud, safety of person or property, violation of our policies, or as otherwise required by law.</p>
                                <p><u>Your Choices.</u></p>
                                <p>You can make the following choices regarding your Personal Data:</p>
                                <p><strong>Promotional Emails.</strong>You may choose during the registration process to provide us with your email address for the purpose of allowing us to send free newsletters, surveys, offers, and other promotional materials related to Grindr and/or the Grindr Services, as well as targeted offers from third parties.  You can stop receiving promotional emails by following the unsubscribe instructions in e-mails that you receive.  If you decide not to receive promotional emails, we may still send you service related communications, and our applications may deliver notifications directly to your mobile device in the Grindr App.</p>
                                <p><strong>Behavioral Advertising On Websites:</strong> Our websites may participate in third party behavioral advertising. This means that a third party may use technology (e.g., a cookie) to collect information about your use of our websites so that they can provide advertising about products and services tailored to your interests.  That advertising may appear either on our website, or on other websites not operated by Grindr.  If you do not want third parties who collect information about your use of our website or applications to tailor any of the advertising that you see, you can opt-out at the
                                    <a href='http://optout.aboutads.info/' className='blue'>Digital Advertising Alliance</a> in the US, the  <a href='http://youradchoices.ca/'   className='blue'>Digital Advertising Alliance of Canada in Canada</a>, or the  <a href='http://www.youronlinechoices.eu/'   className='blue'>European Digital Advertising Alliance</a> in Europe.</p>
                                <p><strong>Behavioral Advertising Within The Grindr App.</strong> If you are using the Grindr Services on an Apple iOS device, you may opt out of behavioral targeting by going into Settings > Privacy > Advertising on your iOS device, or visiting AppleÕs website for more information.  To opt out on an Android device, open the Google Settings,Ó click on AdsÓ and enable Opt out of interest based ads.Ó</p>

                                <p><strong>Behavioral Advertising Outside Of The Grindr App.</strong>Grindr works with advertisers who wish to distribute relevant and interesting ads to Grindr users while the users are on other apps or websites not operated by Grindr.  If you donÕt want advertisements sent to you on those apps or websites because of your affiliation with Grindr, you may change the Behavioral Advertising settings on your device (discussed above) and/or opt out through the <a href='http://optout.aboutads.info/' className='blue'>Digital Advertising Alliance</a> in the US, the <a href='http://youradchoices.ca/'  className='blue'>Digital Advertising Alliance</a> of Canada in Canada, or the <a href='http://www.youronlinechoices.eu/'  className='blue'>European Digital Advertising Alliance</a> in Europe.</p>
                                <p><strong>Effect Of Opting Out Of Behavioral Advertising.</strong>Please note that opting-out of behavioral advertising does not mean that you will not receive advertising while using the Grindr Services.  It will, however, exclude you from interest-based advertising conducted through participating networks, as provided by their policies and choice mechanisms.</p>
                                <p><strong>Changes To Your Personal Data. </strong>Grindr relies on you to update and correct your Personal Data.  You can modify or delete your profile within the Grindr Services.  Please note that Grindr may keep historical information and content in our backup files and archives as permitted by law and to the extent we anticipate that the information may be required in connection with the original purpose of the collection, or as otherwise permitted or required by law.  </p>
                                <p><strong>Deletion Of Your Personal Data.</strong>Typically we retain your Personal Data for the period necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required for the operation of the Grindr Services or permitted by law.  You may, however, request that we delete your Personal Data.  All requests must be directed to the contact in the Contact InformationÓ section of the Grindr Services.  We may also decide to delete your data at any time if we believe that the data is incomplete, inaccurate, or that our continued use and storage are contrary to our obligations to other individuals or third parties.  When we delete Personal Data, it will be removed from our active database, but in some circumstances, it may remain in certain archives where it is not practical or possible to delete it. In addition, we may keep your Personal Data and usage history (which includes a history of text or photos that have been censored, banned) as needed to comply with our legal obligations, resolve disputes, and/or enforce any of our agreements.</p>
                                <p><strong>Revocation Of Consent.</strong>The Grindr Services relies on the processing of Personal Data that you have provided. If you revoke your consent for the processing of Personal Data, then we will no longer be able to provide the Grindr Services. In some cases, we may limit or deny your request if the law permits or requires us to do so, or if we are unable to adequately verify your identity.</p>
                                <p><strong>Access To Your Personal Data.</strong>If required by law, upon request, Grindr will grant a user reasonable access to the Personal Data that Grindr holds about the user. All requests must be directed to the contact in the Contact InformationÓ section of the Grindr Services.</p>
                                <p><u>How We Protect Personal Information</u></p>
                                <p>No method of transmission over the Internet, or method of electronic storage, is fully secure. While Grindr uses reasonable efforts to protect your Personal Data from unauthorized access, use, or disclosure, Grindr cannot guarantee the security of your Personal Data. In the event that we are required by law to inform you of any unauthorized access to your Personal Data, we may notify you electronically, in writing, or by telephone, if permitted to do so by law.</p>
                                <p><u>Miscellaneous Information</u></p>
                                <p>The following additional information relates to our privacy practices:</p>
                                <p><strong>Permissible Age.</strong>The Grindr Services are intended for users 18 years of age and older only (twenty-one (21) years of age in places where eighteen (18) years is not the age of majority). We do not intentionally gather Personal Data about visitors who are under the age of majority. If you are aware that a child or minor has submitted Personal Data on the Grindr Services, please contact us using the information provided below so that we can take appropriate action.</p>
                                <p><strong>Transmission Of Data To Other Countries.</strong>Your Personal Data may be processed in the country in which it was collected and in other countries, including the United States, where laws regarding Personal Data may be less stringent than the laws in your country.  Therefore, in some circumstances, you might be left without a legal remedy in the event of a privacy breach. By submitting your Personal Data, you agree to this transfer, storage and/or processing, including all associated risks.</p>
                                <p><strong>Third Party Applications/Websites.</strong>We have no control over, do not review, and cannot be responsible for other websites or applications.  If you click on a link to another website or third party application, the terms of this Privacy Policy do not apply.</p>
                                <p><strong>Contact Information.</strong>Grindr welcomes your comments or questions regarding this Privacy Policy. Please contact us at the following:</p>

                                <div className='mail-add'>
                                    <p><a className='orange'>privacy@grindr.com</a></p>
                                    <p>Mailing Address:</p>
                                    <p>Grindr LLC</p>
                                    <p>PO Box 69176</p>
                                    <p>West Hollywood, CA 90069</p>
                                </div>

                                <p>Grindr will also initiate an investigation if you contact us with a complaint against our privacy practices or a concern that our practices do not conform to the requirements in your jurisdiction.  We will attempt, where practical, to ensure ongoing compliance with any legal obligations.</p>
                                <p><strong>Changes To This Privacy Policy.</strong>If we make a material change to this policy we will, at a minimum, attempt to notify you of that change either by sending an e-mail to the last e-mail address that you provided to us (if any) or by notifying you when you log into the Grindr Services.  Continued use of the Grindr Services indicates your agreement that any information relating to you, regardless of when it was collected, will be governed by GrindrÕs current policy.</p>
                                <p><strong>Last Revised: August 9, 2017</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        )
    }
}


export default Policy







